export const api = {
    SET_DEVICE: 'SET_DEVICE',
    HOMEPAGE_CONTENT_FETCH: 'HOMEPAGE_CONTENT_FETCH',
    HOMEPAGE_CONTENT_FETCH_SUCCESS: 'HOMEPAGE_CONTENT_FETCH_SUCCESS',
    HOMEPAGE_CONTENT_FETCH_FAIL: 'HOMEPAGE_CONTENT_FETCH_FAIL',
}

export const routes = {
    HOMEPAGE: '/homepage',
}
