export const api = {
    SET_DEVICE: 'SET_DEVICE',
    INFO_DRAWER_TOGGLE: 'INFO_DRAWER_TOGGLE',
    MENU_DRAWER_TOGGLE: 'MENU_DRAWER_TOGGLE',
    HOMEPAGE_CONTENT_FETCH: 'HOMEPAGE_CONTENT_FETCH',
    HOMEPAGE_CONTENT_FETCH_SUCCESS: 'HOMEPAGE_CONTENT_FETCH_SUCCESS',
    HOMEPAGE_CONTENT_FETCH_FAIL: 'HOMEPAGE_CONTENT_FETCH_FAIL',
    INFO_CONTENT_FETCH: 'INFO_CONTENT_FETCH',
    INFO_CONTENT_FETCH_SUCCESS: 'INFO_CONTENT_FETCH_SUCCESS',
    INFO_CONTENT_FETCH_FAIL: 'INFO_CONTENT_FETCH_FAIL',
    CATEGORY_CONTENT_FETCH: 'CATEGORY_CONTENT_FETCH',
    CATEGORY_CONTENT_FETCH_SUCCESS: 'CATEGORY_CONTENT_FETCH_SUCCESS',
    CATEGORY_CONTENT_FETCH_FAIL: 'CATEGORY_CONTENT_FETCH_FAIL',
}

export const routes = {
    HOMEPAGE: '/homepage',
    INFO: '/about',
    CATEGORY: '/category',
}
